### ISSUE TITLE
BreakingNewsDemo: Joda time throws IllegalArgumentException with different locale set.

### ISSUE THREAD

**Issue by carschno** [numenta/htm.java-examples#9]
When I run the BreakingNewsDemo, I get the following exception:

    Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: Invalid format: "Fri Feb 01 12:52:15  2013" is malformed at "i Feb 01 12:52:15  2013"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:899)
	at io.cortical.twitter.TweetUtilities.getCreateDate(TweetUtilities.java:127)
	at io.cortical.twitter.TweetUtilities.getCreateDate(TweetUtilities.java:116)
	at io.cortical.twitter.TweetUtilities.sortTweet(TweetUtilities.java:153)
	at io.cortical.twitter.TweetUtilities.lambda$1(TweetUtilities.java:73)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:387)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.numenta.nupic.examples.cortical_io.breakingnews.BreakingNewsDemo.start(BreakingNewsDemo.java:172)
	at org.numenta.nupic.examples.cortical_io.breakingnews.BreakingNewsDemo.lambda$4(BreakingNewsDemo.java:335)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at org.numenta.nupic.examples.cortical_io.breakingnews.BreakingNewsDemoView.lambda$13(BreakingNewsDemoView.java:242)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$50(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)

It turns out that the reason for this has been that the system locale was set to de_DE. Setting it to the default, and everything works as expected.

The actual problem is apparently rooted in the TweetUtilities package to which I couldn't find the sources though.

**Comment by cogmission** [comment]
Hi @carschno,

How did you set the locale at the system level so that I can reproduce this?

**Comment by thetoucan** [comment]
For people on Windows, I had the same issue and could solve by using the following command to set US locale for JVM:
setx _JAVA_OPTIONS "-Duser.country=US -Duser.language=en" /m

**Comment by cogmission** [comment]
Closing this as it seems to be a local "Locale" issue.

**Comment by carschno** [comment]
@cogmission sorry, I had forgoten about this issue.
As far as I remember, the locale on my Linux system was `DE_de` (default) which results in a decimal format `###,##`. The comma as a decimal separator presumably caused the exception, because English locales expect `###.##`.

**Comment by cogmission** [comment]
@carschno Hi, Thanks! Yep that makes sense. I'll see if I can make a change to do the tweet formatting in a way which first discovers the current "Locale".

**Comment by carschno** [comment]
@cogmission it might suffice (or even be better) to explicitly set the locale to `US_en` before writing and reading data, rather than using the system locale.
